version: '3.8'

services:
  otomoto-db:
    image: mongo
    env_file:
      - .env
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

  otomoto-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - otomoto-db
