version: '3.8'

services:
  otomoto-db:
    image: mongo
    env_file:
      - .env
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

#  You can use mongo-express to manage local database
  otomoto-mongo-express:
    image: mongo-express:1.0.0-18-alpine3.18
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@otomoto-db:27017/
      PORT: 8081

  otomoto-bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - otomoto-db
